/* 
Average Population of Each Continent
-two solutions: one with join, one without */
SELECT COUNTRY.CONTINENT, FLOOR(AVG(CITY.POPULATION))
FROM CITY JOIN COUNTRY ON CITY.COUNTRYCODE=COUNTRY.CODE
/* 
FROM CITY, COUNTRY
WHERE CITY.COUNTRYCODE=COUNTRY.CODE
*/
GROUP BY COUNTRY.CONTINENT
