/*
The Report
Enter your query here.
*/
SELECT
CASE
    WHEN GRADES.GRADE < 8 THEN null
    ELSE STUDENTS.NAME
END,
GRADES.GRADE, STUDENTS.MARKS
FROM STUDENTS JOIN GRADES ON STUDENTS.MARKS >= GRADES.min_mark AND STUDENTS.MARKS <= GRADES.max_mark
ORDER BY GRADES.GRADE DESC, STUDENTS.NAME ASC
